name: e_recycle_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:

  confetti: ^0.7.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  scratcher: ^2.3.0
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.4
  sqflite: ^2.3.0
  path: ^1.8.0
  animations: ^2.0.7
  intl: ^0.18.1
  webview_flutter: ^4.2.2
  url_launcher: ^6.2.4
  provider: ^6.0.5
  gsheets: ^0.4.2

  font_awesome_flutter: ^10.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0

  permission_handler: ^11.3.1
  image_picker: ^1.0.7

  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.0
  http: ^0.13.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.6.0







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/world.jpeg
    - images/1.png
    - images/2.png
    - images/home.png
    - images/bin.png
    - images/dustbin.png
    - images/logo.png
    - images/login.png
    - images/signup1.jpeg
    - images/greenery.png
    - images/garbage.png
    - assets/credentials.json
    - assets/html/map.html
    - assets/html/index.html






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
